Bug: We were storing a pami_type_t* into a pami_type_t
  After undoing the typedefs, we were storing a void** into a void*,
  which is allowed.  The new prototype code using anonymous struct
  pointers for opaque types caught this:

  buildtools/pami/algorithms/protocols/ambcast/AMBroadcastT.h:171:
  error: cannot convert ‘__pami_type_t**’ to ‘__pami_type_t*’ in assignment

Signed-off-by: Joe Ratterman <jratt@us.ibm.com>